name: Android CI

on:
  pull_request:
    branches: [ master, dev ]
  push:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create `google-services.json` app file
        run: cat /home/runner/work/marketplace-app/marketplace-app/app/google-services.json | base64

      - name: Create `google-services.json` data file
        run: cat /home/runner/work/marketplace-app/marketplace-app/data/google-services.json | base64

      - name: Fill :app `google-services.json` with content
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > /home/runner/work/marketplace-app/marketplace-app/app/google-services.json

      - name: Fill :data `google-services.json` with content
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > /home/runner/work/marketplace-app/marketplace-app/data/google-services.json

      - name: Add api key to local.properties
        env:
          PROPS_FILE: /home/runner/work/marketplace-app/marketplace-app/local.properties
          API_KEY: ${{ secrets.API_KEY }}
        run: echo DUMMYPRODUCTSAPIKEY=$API_KEY > $PROPS_FILE

      - name: Assemble
        run: ./gradlew assemble

      - name: Run tests
        run: ./gradlew test
